# Operaciones lógicas con arreglos

In [1]:
import numpy as np

In [2]:
arreglo1 = np.array([3, 12, 15, 16, 3])
arreglo1

array([ 3, 12, 15, 16,  3])

In [8]:
type(arreglo1[0])

numpy.int64

In [ ]:
np.binary_repr(arreglo1[1], width=64)

: 

In [3]:
arreglo2 = np.array([12, 3, 8, 7, 2])
arreglo2

array([12,  3,  8,  7,  2])

In [5]:
arreglo_not = np.bitwise_not(arreglo1)
arreglo_not

array([ -4, -13, -16, -17,  -4])

In [14]:
type(arreglo_not[0])

numpy.int64

In [12]:
np.binary_repr(arreglo_not[0], width=64)

'1111111111111111111111111111111111111111111111111111111111111100'

In [7]:
arreglo_xor = np.bitwise_xor(arreglo1, arreglo2)
arreglo_xor

array([15, 15,  7, 23,  1])

In [6]:
arreglo_or = np.bitwise_or(arreglo1, arreglo2)
arreglo_or

array([15, 15, 15, 23,  3])

In [5]:
arreglo_and = np.bitwise_and(arreglo1, arreglo2)
arreglo_and

array([0, 0, 8, 0, 2])

In [ ]:
np.bitwise