# Broadcasting

In [5]:
import numpy as np

In [6]:
import random
lista = [random.randint(1,11) for _ in range(10)]
lista

[1, 8, 9, 10, 6, 11, 9, 11, 9, 4]

In [7]:
lista +5

TypeError: can only concatenate list (not "int") to list

In [8]:
resultado = []
for e in lista:
    resultado.append(e+5)
resultado

[6, 13, 14, 15, 11, 16, 14, 16, 14, 9]

In [10]:
# Con un for
x = np.arange(1,6)
lr = []
for e in x:
    lr.append(e+5)

r1 = np.array(lr)
x, r1

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [9]:
# Broadcasting tensor de 1 dim con escalar
a = np.arange(1,11,2)

r = a + 5
a,r

(array([1, 3, 5, 7, 9]), array([ 6,  8, 10, 12, 14]))

In [25]:
# Broadcasting tensor de 2 dim con escalar
aleatorios = np.random.randint(1,11, (3,4))
aleatorios

array([[ 8,  4,  9,  2],
       [ 9,  8,  1,  9],
       [ 6,  9, 10,  6]])

In [26]:
r2 = aleatorios *10
r2

array([[ 80,  40,  90,  20],
       [ 90,  80,  10,  90],
       [ 60,  90, 100,  60]])

In [27]:
# Broadcasting tensor de 3 dim con escalar
cubo_unos = np.ones((3,3,3))
cubo_unos

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
r3 = cubo_unos + 2
r3

array([[[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]])

In [28]:
aleatorios, a

(array([[ 8,  4,  9,  2],
        [ 9,  8,  1,  9],
        [ 6,  9, 10,  6]]),
 array([1, 3, 5, 7, 9]))

In [29]:
r4 = aleatorios + a
r4

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [30]:
c = np.arange(4)
aleatorios, c

(array([[ 8,  4,  9,  2],
        [ 9,  8,  1,  9],
        [ 6,  9, 10,  6]]),
 array([0, 1, 2, 3]))

In [31]:
r5 = aleatorios + c
r5, aleatorios, c

(array([[ 8,  5, 11,  5],
        [ 9,  9,  3, 12],
        [ 6, 10, 12,  9]]),
 array([[ 8,  4,  9,  2],
        [ 9,  8,  1,  9],
        [ 6,  9, 10,  6]]),
 array([0, 1, 2, 3]))

In [35]:
a2 = np.arange(3).reshape((3,1))
aleatorios, a2

(array([[ 8,  4,  9,  2],
        [ 9,  8,  1,  9],
        [ 6,  9, 10,  6]]),
 array([[0],
        [1],
        [2]]))

In [36]:
r6 = aleatorios + a2
r6, aleatorios, a2

(array([[ 8,  4,  9,  2],
        [10,  9,  2, 10],
        [ 8, 11, 12,  8]]),
 array([[ 8,  4,  9,  2],
        [ 9,  8,  1,  9],
        [ 6,  9, 10,  6]]),
 array([[0],
        [1],
        [2]]))

In [37]:
a2, a

(array([[0],
        [1],
        [2]]),
 array([1, 3, 5, 7, 9]))

In [38]:
a2+a

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 3,  5,  7,  9, 11]])

In [22]:
a+a2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [23]:
a , c

(array([0, 1, 2]), array([0, 1, 2, 3]))

In [24]:
a+c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [25]:
a2,c

(array([[0],
        [1],
        [2]]),
 array([0, 1, 2, 3]))

In [26]:
a2+c

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])