# Operaciones con arreglos en Numpy

In [3]:
import numpy as np

In [5]:
import math as m

In [13]:
grados = np.array([i for i in range(0, 361, 1)], dtype='float')
grados

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100., 101., 102., 103., 104., 105., 106., 107., 108., 109.,
       110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131.,
       132., 133., 134., 135., 136., 137., 138., 139., 140., 141., 142.,
       143., 144., 145., 146., 147., 148., 149., 15

In [14]:
m.pi

3.141592653589793

In [15]:
np_radianes= grados*(m.pi/180)
np_radianes

array([0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317,
       0.08726646, 0.10471976, 0.12217305, 0.13962634, 0.15707963,
       0.17453293, 0.19198622, 0.20943951, 0.2268928 , 0.2443461 ,
       0.26179939, 0.27925268, 0.29670597, 0.31415927, 0.33161256,
       0.34906585, 0.36651914, 0.38397244, 0.40142573, 0.41887902,
       0.43633231, 0.45378561, 0.4712389 , 0.48869219, 0.50614548,
       0.52359878, 0.54105207, 0.55850536, 0.57595865, 0.59341195,
       0.61086524, 0.62831853, 0.64577182, 0.66322512, 0.68067841,
       0.6981317 , 0.71558499, 0.73303829, 0.75049158, 0.76794487,
       0.78539816, 0.80285146, 0.82030475, 0.83775804, 0.85521133,
       0.87266463, 0.89011792, 0.90757121, 0.9250245 , 0.9424778 ,
       0.95993109, 0.97738438, 0.99483767, 1.01229097, 1.02974426,
       1.04719755, 1.06465084, 1.08210414, 1.09955743, 1.11701072,
       1.13446401, 1.15191731, 1.1693706 , 1.18682389, 1.20427718,
       1.22173048, 1.23918377, 1.25663706, 1.27409035, 1.29154

In [16]:
fsin = np.sin(np_radianes)
fsin

array([ 0.00000000e+00,  1.74524064e-02,  3.48994967e-02,  5.23359562e-02,
        6.97564737e-02,  8.71557427e-02,  1.04528463e-01,  1.21869343e-01,
        1.39173101e-01,  1.56434465e-01,  1.73648178e-01,  1.90808995e-01,
        2.07911691e-01,  2.24951054e-01,  2.41921896e-01,  2.58819045e-01,
        2.75637356e-01,  2.92371705e-01,  3.09016994e-01,  3.25568154e-01,
        3.42020143e-01,  3.58367950e-01,  3.74606593e-01,  3.90731128e-01,
        4.06736643e-01,  4.22618262e-01,  4.38371147e-01,  4.53990500e-01,
        4.69471563e-01,  4.84809620e-01,  5.00000000e-01,  5.15038075e-01,
        5.29919264e-01,  5.44639035e-01,  5.59192903e-01,  5.73576436e-01,
        5.87785252e-01,  6.01815023e-01,  6.15661475e-01,  6.29320391e-01,
        6.42787610e-01,  6.56059029e-01,  6.69130606e-01,  6.81998360e-01,
        6.94658370e-01,  7.07106781e-01,  7.19339800e-01,  7.31353702e-01,
        7.43144825e-01,  7.54709580e-01,  7.66044443e-01,  7.77145961e-01,
        7.88010754e-01,  

In [19]:
radianes2 = np.radians(np.array([i for i in range(0,191,10)], dtype='float').reshape(4,5))
radianes2

array([[0.        , 0.17453293, 0.34906585, 0.52359878, 0.6981317 ],
       [0.87266463, 1.04719755, 1.22173048, 1.3962634 , 1.57079633],
       [1.74532925, 1.91986218, 2.0943951 , 2.26892803, 2.44346095],
       [2.61799388, 2.7925268 , 2.96705973, 3.14159265, 3.31612558]])

In [20]:
fcos = np.cos(radianes2)
fcos

array([[ 1.00000000e+00,  9.84807753e-01,  9.39692621e-01,
         8.66025404e-01,  7.66044443e-01],
       [ 6.42787610e-01,  5.00000000e-01,  3.42020143e-01,
         1.73648178e-01,  6.12323400e-17],
       [-1.73648178e-01, -3.42020143e-01, -5.00000000e-01,
        -6.42787610e-01, -7.66044443e-01],
       [-8.66025404e-01, -9.39692621e-01, -9.84807753e-01,
        -1.00000000e+00, -9.84807753e-01]])

In [22]:
valores_equidistantes = np.linspace(0,1,11)
valores_equidistantes

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
# Crear una matriz de 100x100 con valores equidistantes entre 0 y 1
# Calcular la tan de todos los valores de dicha matriz
ejercicio1_examen = np.tan(np.linspace(0,1, 100*100).reshape(100,100))
ejercicio1_examen

array([[0.00000000e+00, 1.00010001e-04, 2.00020005e-04, ...,
        9.70127442e-03, 9.80129393e-03, 9.90131364e-03],
       [1.00013335e-02, 1.01013537e-02, 1.02013740e-02, ...,
        1.97045198e-02, 1.98045688e-02, 1.99046183e-02],
       [2.00046681e-02, 2.01047183e-02, 2.02047689e-02, ...,
        2.97117087e-02, 2.98118073e-02, 2.99119065e-02],
       ...,
       [1.45950474e+00, 1.45981783e+00, 1.46013102e+00, ...,
        1.49030736e+00, 1.49062954e+00, 1.49095182e+00],
       [1.49127419e+00, 1.49159666e+00, 1.49191923e+00, ...,
        1.52300924e+00, 1.52334128e+00, 1.52367342e+00],
       [1.52400566e+00, 1.52433800e+00, 1.52467045e+00, ...,
        1.55672277e+00, 1.55706519e+00, 1.55740772e+00]])