In [1]:

import numpy as np
# Ejercicio 1 .array
# Crea un arreglo llamado "arreglo1" con los números: 10, 20, 30, 40
arreglo1D = np.array([10, 20, 30, 40,50,60,70,80,90,100])
arreglo1D

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
# arreglod e dos dimensiones    
arreglo2D = np.array([[10, 20, 30, 40],[10, 20, 30, 40]])
print(arreglo2D,"\n"," y tiene ",arreglo2D.shape[0]," filas y ",arreglo2D.shape[1]," columnas")

[[10 20 30 40]
 [10 20 30 40]] 
  y tiene  2  filas y  4  columnas


In [3]:
# crea una rreglo de una dimension deciamles
arregloDecimal = np.array([1.1, 3.7, 3.3, 4.4])
# Muestra su tipo de dato con el atributo dtype
arregloDecimal.dtype

dtype('float64')

In [4]:
arrange1 = np.arange(24)
# arrange sirve para crear un arreglo de una dimension con un rango de valores
# y un paso determinado
# en este caso el rango es de 0 a 24 y el paso es de 1
print("Array con arange:", arrange1)

Array con arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [5]:
arrange2 = np.arange(5, 24)
print("Array con arange:", arrange2)

Array con arange: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
arrange3 =  np.arange(5, 35, 5)
print("Array con arange:", arrange3, "y tiene una forma de:", arrange3.shape)

Array con arange: [ 5 10 15 20 25 30] y tine una forma de: (6,)


In [9]:
arrange3Resahpe = arrange3.reshape(6,1)
#reshape necesita que el numero de elementos del arreglo original sea igual
#  al numero de elementos del nuevo arreglo
print("", arrange3Resahpe, "y tiene una forma de:", arrange3.shape)

 [[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]] y tiene una forma de: (6,)


In [13]:
Arrange2D = np.arange(5, 35, 5).reshape(3,2)
print("Array 2D con arange: \n", Arrange2D, "y tiene una forma de:", Arrange2D.shape)

Array 2D con arange: 
 [[ 5 10]
 [15 20]
 [25 30]] y tiene una forma de: (3, 2)
