# Agregacion de elementos a un array

In [2]:
import numpy as np

In [3]:
# Tensor de una dimension con 3 elementos con valores enteros igual a 1 
array1 = np.ones(3, dtype='int16')
array1

array([1, 1, 1], dtype=int16)

In [4]:
# Tensor de una dimension con 3 elementos con valores enteros iguales a 0
array2 = np.zeros(3, dtype='int16')
array2

array([0, 0, 0], dtype=int16)

In [5]:
# Lista con 2 elementos que son arreglos d eNumpy
array3 = [array1, array2]
print(array3)

[array([1, 1, 1], dtype=int16), array([0, 0, 0], dtype=int16)]


In [6]:
array3[0]

array([1, 1, 1], dtype=int16)

In [7]:
array4 = np.append(array1, array2)
array4

array([1, 1, 1, 0, 0, 0], dtype=int16)

In [8]:
array5= np.random.random(3)
array5

array([0.37330575, 0.3804431 , 0.46488894])

In [9]:
array6 = np.append(array1, array5)
array6

array([1.        , 1.        , 1.        , 0.37330575, 0.3804431 ,
       0.46488894])

In [10]:
array7 = np.array(['a','b', 'c'])
array7

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
array8 = np.append(array5, array7)
array8

array(['0.3733057450053098', '0.3804430980088599', '0.4648889400255779',
       'a', 'b', 'c'], dtype='<U32')

In [12]:
float(array8[0])+float(array8[1])

0.7537488430141697

In [13]:
array8[0]+array8[1]

'0.37330574500530980.3804430980088599'

In [14]:
array1

array([1, 1, 1], dtype=int16)

In [15]:
array2

array([0, 0, 0], dtype=int16)

In [16]:
array11 = array1.reshape(1,3)
array11

array([[1, 1, 1]], dtype=int16)

In [17]:
array22 = array2.reshape(1,3)
array22

array([[0, 0, 0]], dtype=int16)

In [18]:
array33 = np.append(array11, array22)
array33

array([1, 1, 1, 0, 0, 0], dtype=int16)

In [19]:
array44 = np.append(array11, array22, axis=0)
array44

array([[1, 1, 1],
       [0, 0, 0]], dtype=int16)

In [20]:
print(array1)
print(array2)

[1 1 1]
[0 0 0]


In [21]:
array55 = np.append(array1, array2, axis=1)
array55

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
arraytemp = np.append(array1, array2, axis=0)
arraytemp

In [ ]:
prueba1 = np.arange(1,13).reshape(3,4)
prueba1

In [ ]:
prueba2 = np.random.normal(0,1,4).reshape(1,4)
prueba2

In [ ]:
prueba3 = np.append(prueba1, prueba2)
prueba3

In [ ]:
prueba4 = np.append(prueba1, prueba2, axis=0)
prueba4

In [ ]:
prueba5 = np.random.normal(100,2,12).reshape(3,4)
prueba5

In [ ]:
prueba6= np.append(prueba1, prueba5)
prueba6

In [ ]:
prueba7= np.append(prueba1, prueba5, axis=0)
prueba7